# Generated by Django 3.2.3 on 2021-05-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='new',
            name='languages',
            field=models.CharField(default='Vietnamese', max_length=100),
        ),
        migrations.AddField(
            model_name='new',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
